spring.application.name=bookstore_mongodb

## mongo db setup
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=bookstore
spring.data.mongodb.uri=mongodb+srv://jasminerrodriguez_db_user:EuZt79dwlbrW3cil@cluster0.7fukpru.mongodb.net/mydb

logging.level.org.springframework.data.mongodb.core=DEBUG

jwt.secret=cpsc449-bookstore-secret-key-must-be-at-least-256-bits-long!
jwt.expiration=84000000